cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from .views import AboutView

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path("about/", AboutView.as_view(), name="about"),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView
from cart.forms import CartAddProductForm
from .models import Category, Product


class AboutView(TemplateView):
    template_name = 'about.html'
    
    def get(self, request, *args, **kwargs): 
        categories = Category.objects.all()  
        context = {'categories': categories}
        return render(request, self.template_name, context)

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
        

    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products
                   })


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form':cart_product_form,
    }
    return render(request,'shop/product/detail.html', context)

shop/templates/shop/product/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{ product.name }}
{% endblock %}

{% block content %}
<!-- Product section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6">
                <img class="mb-5 mb-md-0" src="
                {% if product.image %}
                    {{ product.image.url }}
                {% else %}
                    {% static "img/no_image.png" %}
                {% endif %}">
            </div>
            <div class="col-md-6">
                <div class="small mb-1"><a class="text-dark text-decoration-none"
                        href="{{ product.category.get_absolute_url }}">Category:
                        {{ product.category }}
                    </a></div>
                <h1 class="display-5 fw-bolder">{{ product.name }}</h1>
                <div class="fs-5 mb-5">
                    <span class="text-decoration-line-through">$45.00</span>
                    <span>$40.00</span>
                </div>
                <p class="lead">{{ product.description|linebreaks }}</p>
                <form action="{% url "cart:cart_add" product.id %}" method="POST">
                    {{ cart_product_form }}
                    {% csrf_token %}
                    <input type="submit" value="Add to cart">
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
<!-- Section-->
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="card mb-4 box-shadow" style="width: 22rem;">
          {% for product in products %}
          <!-- Sale badge-->
          <div class="badge bg-danger text-white position-absolute" style="top: 0.5rem; right: 0.5rem">
            Sale
          </div>
          <!-- Product image-->
          <div class="card-body bordered">
            <a href="{{ product.get_absolute_url }}">
              <img class="card-image img-fluid bordered"
                src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" />
            </a>          
          </div>
          <!-- Product details-->
          <div class="card-body p-4">
            <div class="text-center">
              <!-- Product name-->
              <h5 class="fw-bolder"><a class="text-dark text-decoration-none"
                  href="{{ product.get_absolute_url }}">{{ product.name }}</a></h5>
              <!-- Product reviews-->
              <div class="d-flex justify-content-center small text-warning mb-2">
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
              </div>
              <!-- Product price-->
              {% comment %} <span class="text-muted text-decoration-line-through">{{product.price }}</span> {% endcomment %}
              {{ product.price }}$
            </div>
            {{ product.description|slice:55 }}...
          </div>
          <!-- Product actions-->
          <div class="card-footer p-8 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
              <a href="{{ product.get_absolute_url }}">
                <button type="button" class="btn btn-outline-success btn-sm mr-3" value="Add to card">View</button>
              </a>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}