cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from .views import AboutView

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path("about/", AboutView.as_view(), name="about"),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView
from cart.forms import CartAddProductForm
from .models import Category, Product


class AboutView(TemplateView):
    template_name = 'about.html'
    
    def get(self, request, *args, **kwargs): 
        categories = Category.objects.all()  
        context = {'categories': categories}
        return render(request, self.template_name, context)

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
        

    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products
                   })


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form':cart_product_form,
    }
    return render(request,'shop/product/detail.html', context)

shop/templates/about.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    About
{% endblock title%}
{% block content %}
<div class='container mt-5'>
    <p class='text-muted'>
        Since its fuse in 2005, Company Name has cut a specialty for itself in the youngsters’ books section of the distributing business. We have some expertise in books implied for offspring of various ages.

        The wide scope of books offered by us incorporates fantasies, moral stories, showed story books, reference books, general learning books, sentence structure books, shading books, action books, sticker books and some more. Every one of these books are accessible in both English and Hindi.

        Our point is to give significant, charming and also animating substance to youngsters that goes much past their normal course books.With this point in view, we treat each book as a work of adoration. Every one of our books are broadly examined, attentively composed and delightfully planned.

        Development and experimentation are indispensable to our methodology towards books. Our broad gathering of books– picture books, sticker books, story and sticker books, 3D Books, spring up books, innovative idea books, curiosity books, topic based books, movement books, and so on – are a declaration to this methodology. This encourages us in making energizing and testing items for youngsters.

        We earnestly trust that books can be an extraordinary wellspring of motivation with the ability to impact and shape youthful personalities. Our books not simply go for building up the scholarly capacities of youngsters, rather they are made with the aim of contributing towards their all encompassing improvement.
    </p>
</div>  
{% endblock %}

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"> 
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %}My shop{% endblock %}</title> 
    {% comment %} Google icons {% endcomment %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <!-- Bootstrap icons-->
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static "css/base.css" %}" rel="stylesheet" />
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-color">
        <div class="container px-4 px-lg-3">
            <a class="navbar-brand" href="{% url 'shop:product_list' %}">BookStore</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mr-auto">
                    <li class="nav-item active"><a class="nav-link" aria-current="page" href="{% url 'shop:product_list' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'shop:about' %}">About</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li {% if not category %}class="selected" {% endif %}><a class="dropdown-item"
                                    href="{% url "shop:product_list" %}">All Products</a></li>
                            {% for c in categories %}
                            <li>
                                <hr class="dropdown-divider" />
                            </li>
                            <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                                <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
                <form class="d-flex">
                    <a class="btn btn-warning" href="{% url "cart:cart_detail" %}" role="button">
                        <i class="bi-cart-fill me-1"></i>
                        {% with total_items=cart|length %}
                        {% if total_items > 0 %}
                            Cart:
                            {{ total_items }} item{{ total_items|pluralize }},
                            ${{ cart.get_total_price }}
                
                        {% else %}
                        Cart is empty
                        {% endif %}
                        {% endwith %}
                        <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>        
                    </a>
                </form>
            </div>
        </div>
    </nav>
    <!-- Header-->
    <header class="header-img">
        {% comment %} <div class=>
          <h1 class="display-3">Hello, world!</h1>
          <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
          <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p>
        </div>{% endcomment %}
    </header> 
    {% block content %}
    {% endblock %}
    <!-- Footer-->
    <footer class="relative-bottom mt-5 py-5 navbar-color">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
   
    
</body>

</html>