cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('done/', views.payment_done, name='done'),
    path('canceled/', views.payment_canceled, name='canceled'),
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
import braintree
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from orders.models import Order
from .tasks import payment_completed


# instantiate Braintree payment gateway
gateway = braintree.BraintreeGateway(settings.BRAINTREE_CONF)

# The payment_process view manages the checkout process
def payment_process(request):
    # You get the current order from the order_id session key, 
    # which was stored previously in the session by the order_create view.
    order_id = request.session.get('order_id')
    # You retrieve the Order object for the given ID or raise an Http404 exception if it is not found.
    order = get_object_or_404(Order, id=order_id)
    # You get sum of total cost of selected items
    total_cost = order.get_total_cost()

    if request.method == 'POST':
        # When the view is loaded with a POST request, you retrieve the 
        # "payment_ method_nonce" to generate a new transaction using "gateway.transaction.sale()"
        nonce = request.POST.get('payment_method_nonce', None)
        # create and submit transaction
        result = gateway.transaction.sale({
            # total amount formatted with two decimal places.
            'amount': f'{total_cost:.2f}',
            # payment_method_nonce: The token nonce generated by Braintree for the payment. 
            'payment_method_nonce': nonce,
            'options': {
                'submit_for_settlement': True
            }
        })
        if result.is_success:
            # mark the order as paid
            order.paid = True
            # store the unique transaction id
            order.braintree_id = result.transaction.id
            order.save()
            # launch asynchronous task
            payment_completed.delay(order.id)
            return redirect('payment:done')
        else:
            return redirect('payment:canceled')
    else:
        # generate token
        client_token = gateway.client_token.generate()
        return render(request,
                      'payment/process.html',
                      {'order': order,
                       'client_token': client_token})


def payment_done(request):
    return render(request, 'payment/done.html')


def payment_canceled(request):
    return render(request, 'payment/canceled.html')

payment/templates/payment/canceled.html
{% extends "base.html" %}

{% block title %}Payment canceled{% endblock %}

{% block content %}
<div class="container">
   <div class="row">
      <div class="col-md-6 mx-auto mt-5">
         <div class="payment">
            <div class="payment_header">
               <div class="check"><i class="bi bi-x-circle-fill"></i></div>
            </div>
            <div class="content">
               <h1 class="text-danger">Your payment has not been processed!</h1>
               <p>There was a problem processing your payment.</p>
               <a href="{% url 'payment:process'%}">Go Back</a>
            </div>
            
         </div>
      </div>
   </div>
</div>
{% endblock %}

payment/templates/payment/done.html
{% extends "base.html" %}

{% block title %}Payment successful{% endblock %}

{% block content %}
<div class="container">
   <div class="row">
      <div class="col-md-6 mx-auto mt-5">
         <div class="payment">
            <div class="payment_header">
               <div class="check"><i class="fa fa-check" aria-hidden="true"></i></div>
            </div>
            <div class="content">
               <h1>Payment Success !</h1>
               <p>Your payment has been processed successfully.</p>
               <a href="/">Go to Home</a>
            </div>
            
         </div>
      </div>
   </div>
</div>
{% comment %} <div class="container mt-4"> 
  <h1 class="alert-heading text-center">Your payment was successful</h4>
  <div class="alert alert-success" role="alert">
    <p class='text-success text-center'>Your payment has been processed successfully.</p>
  </div>
</div> {% endcomment %}
  
{% endblock %}

payment/templates/payment/process.html
{% extends "base.html" %}

{% block title %}Pay by credit card{% endblock %}

{% block content %}

<section class="py-5 container">
  <div class="card mx-auto" style="width: 25rem; border-radius: 20px; background-color: #ff6600;">
    <div class="card-body">
    <h1 class="card-title">Pay by credit card</h1>
    <form id="payment" method="post">

      <label for="card-number">Card Number</label>
      <div id="card-number" class="field"></div>

      <label for="cvv">CVV</label>
      <div id="cvv" class="field"></div>

      <label for="expiration-date">Expiration Date</label>
      <div id="expiration-date" class="field"></div>

      <input type="hidden" id="nonce" name="payment_method_nonce" value="">
      {% csrf_token %}
      <input class="offset-9" type="submit" value="Pay now">
    </form>
    </div>
    <!-- includes the Braintree JS client SDK -->
    <script src="https://js.braintreegateway.com/web/3.58.0/js/client.min.js"></script>
    <script src="https://js.braintreegateway.com/web/3.58.0/js/hosted-fields.min.js"></script>
    <script>
      var form = document.querySelector('#payment');
      var submit = document.querySelector('input[type="submit"]');

      braintree.client.create({
        authorization: '{{ client_token }}'
      }, function (clientErr, clientInstance) {
        if (clientErr) {
          console.error(clientErr);
          return;
        }

        braintree.hostedFields.create({
          client: clientInstance,
          styles: {
            'input': {
              'font-size': '13px',
            },
            'input.invalid': {
              'color': 'red'
            },
            'input.valid': {
              'color': 'green'
            }

          },
          fields: {
            number: {
              selector: '#card-number'
            },
            cvv: {
              selector: '#cvv'
            },
            expirationDate: {
              selector: '#expiration-date'
            }
          }
        }, function (hostedFieldsErr, hostedFieldsInstance) {
          if (hostedFieldsErr) {
            console.error(hostedFieldsErr);
            return;
          }

          submit.removeAttribute('disabled');

          form.addEventListener('submit', function (event) {
            event.preventDefault();

            hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
              if (tokenizeErr) {
                console.error(tokenizeErr);
                return;
              }
              // set nonce to send to the server
              document.getElementById('nonce').value = payload.nonce;
              // submit form
              document.getElementById('payment').submit();
            });
          }, false);
        });
      });
    </script>
  </div>
</section>

{% endblock %}